In [1]:
!conda list numpy

# packages in environment at /Users/deepdoshi/anaconda3:
#
numpy                     1.13.3           py36h2cdce51_0  
numpydoc                  0.7.0            py36he54d08e_0  


##### NumPy v/s Python execution time comparison

In [3]:
import time
import numpy as np

In [4]:
x = np.random.random(100000000)  # create an array of 100 million random numbers

In [7]:
# Find mean using normal python
start = time.time()
sum(x)/len(x)
print(time.time() - start)

8.12062406539917


In [8]:
# Find mean using numpy
start = time.time()
np.mean(x)
print(time.time() - start)

0.06761312484741211


###### NumPy Arrays

In [9]:
x = np.array([1, 2, 3, 4, 5])

In [10]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
x.dtype    # dtype returns the type of the element in the array

dtype('int64')

In [12]:
x.shape   # returns tuple of n positive integers that specifies sizes of each dimension

(5,)

In [14]:
y = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
y.shape

(3, 3)

In [16]:
y.size     # total number of elements in an array

9

In [17]:
z = np.array(['Hello', 'World'])
print(z)

['Hello' 'World']


In [19]:
print('shape: ', z.shape)
print('type: ', type(z))
print('dtype: ', z.dtype)

shape:  (2,)
type:  <class 'numpy.ndarray'>
dtype:  <U5


In [21]:
w = np.array([1,2,'World'])
print(w)
print('shape: ', w.shape)
print('type: ', type(w))
print('dtype: ', w.dtype)

['1' '2' 'World']
shape:  (3,)
type:  <class 'numpy.ndarray'>
dtype:  <U21


In [23]:
v = np.array([1, 2, 3.5])
print(v, v.dtype)

[ 1.   2.   3.5] float64


In [24]:
s = np.array([3.5, 2.4, 5.4], dtype=np.int64)
print(s)
print('dtype: ', s.dtype)

[3 2 5]
dtype:  int64


In [26]:
t = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
np.save('my_array', t)

In [28]:
r = np.load('my_array.npy')
print(r)

[1 2 3 4 5 6 7 8 9 0]
