### NumPy Practice

In [2]:
import numpy as np

In [7]:
# Create a 4 x 4 ndarray of all even numbers from 2 to 32 (inclusive)
a1 = np.arange(2,33,2).reshape(4,4)
print('ans = \n',a1)
print()
print('Dimension of ans: ', a1.shape)

ans = 
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

Dimension of ans:  (4, 4)


##### NumPy array slicling

In [9]:
# Create a rank 1 ndarray
a2 = np.array([1,2,3,4,5])

print(a2)
print()

# Access elements with positive indices
print("First element in a2: ", a2[0])
print("Second element in a2: ", a2[1])
print("Fifth element in a2: ", a2[4])
print("Last element in a2: ", a2[len(a2)-1])

print()

# Access same elements with negative indices
print("Last element in a2:", a2[-1])
print("Second elment in a2: ", a2[-4])
print("First element in a2: ", a2[-5])

[1 2 3 4 5]

First element in a2:  1
Second element in a2:  2
Fifth element in a2:  5
Last element in a2:  5

Last element in a2: 5
Second elment in a2:  2
First element in a2:  1


##### NumPy arrays are mutable

In [12]:
print("Array \n a2: ", a2)

print()

# Modify 4th element of the above array
a2[3] = 90

print("Modified array \n a2: ", a2)

Array 
 a2:  [ 1  2  3 90  5]

Modified array 
 a2:  [ 1  2  3 90  5]


In [20]:
# Create a rank 2 ndarray
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print()

# Slice an element from rank 2 array
print('Element (0,2) of array \n a3:', a3[0,2])

print()

print('Array \n a3: \n', a3)

print()

# Modify content of above array
a3[2,1] = 21

print("Modified array \n a3: \n", a3)


Element (0,2) of array 
 a3: 3

Array 
 a3: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Modified array 
 a3: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7 21  9]]


In [4]:
# Create rank 1 ndarray
a4 = np.arange(1,21)

print("a4: ", a4)

print("a4[3:] = ", a4[3:])
print("a4[:7] = ", a4[:7])
print("a4[3:20] = ", a4[0:20])

a4:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
a4[3:] =  [ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
a4[:7] =  [1 2 3 4 5 6 7]
a4[3:20] =  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [23]:
# Create a rank 2 array

a5 = np.arange(20).reshape(4,5)

print("a5 =\n", a5)
print()

# Select all the elements that are in 2nd through 4th rows and 3rd through 4th columns
a51 = a5[1:4,2:5]    # [row,cloumn], also end indices are exclusive

print("a51 = \n", a51)
print()

a52 = a5[1:,2:5]   # second method
print("a52 =\n", a52)
print()

# Select all the elements from 1st through 3rd row and 2nd through 4th column
a53 = a5[:3,2:4]
print("a53 =\n", a53)
print()

# Select all the elements in 3rd row
a54 = a5[2,:]
print("a54 =", a54)
print()

# Select all the elements in 3rd column
a55 = a5[:,2]
print("a55 =", a55)
print()

# Select all the elements from 3rd column but with a rank 2 array
a56 = a5[:, 2:3]
print("a56 =\n", a56)
print("a5 =\n", a5)

a5 =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

a51 = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

a52 =
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

a53 =
 [[ 2  3]
 [ 7  8]
 [12 13]]

a54 = [10 11 12 13 14]

a55 = [ 2  7 12 17]

a56 =
 [[ 2]
 [ 7]
 [12]
 [17]]
a5 =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [24]:
# Create a 4 x 5 ndarray
a6 = np.arange(20).reshape(4,5)

print("a6 =\n", a6)
print()

# Select all the elements that are in 2nd through 4th rows and 3rd through 4th columns
a61 = a6[1:4,2:5]

print("a61 =\n", a61)
print()

# Change last element of the above array
a61[2,2] = 222

print("a61 =\n", a61)
print()
print("a6 =\n", a6)   
# array slicing doesn't copy all the elements to new array, it's just different name for the same array

a6 =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

a61 =
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

a61 =
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 222]]

a6 =
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 222]]
